#lang racket
(define (exit) #f)
(define (map op lst)
  (if (null? lst)
      '()
      (cons (op (car lst))
            (map op (cdr lst)))))
  
(define (super-map op . w)
  (define len (length (car w)))
  (define (get-n-list n)
    (map (lambda (x) (list-ref x n)) w))
  (define (loop i)
    (if (= i len)
        '()
        (cons (apply op (get-n-list i)) (loop (+ i 1)))))
  (loop 0))
(define (myloop)
  (let ((a (read))
        (b (read))
        (c (read)))
    (if (eq? a eof)
        (void)
        (begin (displayln (super-map + a b c)) 
               (displayln (super-map (lambda (x y) (+ x (* 2 y) )) a b ))
               (myloop)))))
(myloop)